version: 2
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
  # Git Submosuldes
  - package-ecosystem: "gitsubmodule"
    directory: "/"
    schedule:
      interval: "daily"
